codecov:
  require_ci_to_pass: true
  token: ${CODECOV_TOKEN}  # 不要直接放token在这里

coverage:
  status:
    project:
      default:
        target: 1
    patch:
      default:
        target: 0

github_checks:
  annotations: false

ignore:
  - '**/tests/**'