# Codecov

codecov:
  token: 43d14d1f-aab0-4b34-ae45-c550fdbc98b2

coverage:
  status:
    project:
      default:
        target: 1
    patch:
      default:
        target: 0

github_checks:
  annotations: false

ignore:
  - '**/tests/**'
