clear all
options.mindim = 6;
options.maxdim = 50;
options.plibs = 's2mpj';
options.max_eval_factor = 200;
options.n_runs = 5;
options.solver_names = {'accelerated-bds', 'nomad'};

feature_names = { ...
    'plain', ...
    'noisy_1e-1', ...
    'noisy_1e-2', ...
    'noisy_1e-3', ...
    'noisy_1e-4', ...
    'linearly_transformed', ...
    'linearly_transformed_noisy_1e-1', ...
    'linearly_transformed_noisy_1e-2', ...
    'linearly_transformed_noisy_1e-3', ...
    'linearly_transformed_noisy_1e-4' ...
};

for k = 1:numel(feature_names)
    options.feature_name = feature_names{k};
    fprintf('Running %d/%d: %s\n', k, numel(feature_names), options.feature_name);
    profile_optiprofiler(options);
end
