function [xopt, fopt, exitflag, output] = lean_evolved_bds_options(fun, x0, options)
%LEAN_EVOLVED_BDS_OPTIONS Experimental options-enabled Lean Evolved BDS.
%
% This file starts as an exact copy of lean_evolved_bds.m, with only the
% function name changed. It is intended for options/switch experiments while
% keeping lean_evolved_bds.m as the fixed reference implementation.
%
% The reference solver mirrors tests/competitors/evolved_bds_solver_lean.py
% in bds_python and keeps only:
%   - ordinary direction cycling within each coordinate block;
%   - BDS-style block partitioning through divide_direction_set.m;
%   - explicit productive direction memory;
%   - Hooke-Jeeves-style iteration-level pattern / momentum extrapolation.

if nargin < 3 || isempty(options)
    options = struct();
end

x0 = x0(:);
n = numel(x0);
options = set_lean_evolved_bds_options(options, n, x0);
MaxFunctionEvaluations = options.MaxFunctionEvaluations;
maxit = MaxFunctionEvaluations;
ftarget = options.ftarget;
num_blocks = options.num_blocks;
StepTolerance = options.StepTolerance;
alpha_all = options.alpha_init;
expand = options.expand;
shrink = options.shrink;
forcing_function = options.forcing_function;
reduction_factor = options.reduction_factor;

D = get_direction_set(n, options);
grouped_direction_indices = divide_direction_set(n, num_blocks, options);

productive_direction_memory_size = options.productive_direction_memory_size;
prod_memory = struct('direction', {}, 'step', {});
momentum = zeros(n, 1);
momentum_decay = options.momentum_decay;

fopt_all = nan(num_blocks, 1);
xopt_all = nan(n, num_blocks);

[f0, f0_real, is_valid] = eval_fun(fun, x0);
nf = 1;
output_xhist = options.output_xhist;
output_alpha_hist = options.output_alpha_hist;
output_block_hist = options.output_block_hist;
output_grad_hist = options.output_grad_hist;
fhist = nan(1, MaxFunctionEvaluations);
xhist = [];
invalid_points = [];
if output_xhist
    xhist = nan(n, MaxFunctionEvaluations);
    xhist(:, nf) = x0;
    if ~is_valid
        invalid_points = [invalid_points, x0];
    end
end
fhist(nf) = f0_real;
alpha_hist = [];
if output_alpha_hist
    alpha_hist(:, 1) = alpha_all(:);
end
block_hist = nan(1, MaxFunctionEvaluations);
num_visited_blocks = 0;
grad_hist = [];
grad_xhist = [];
grad_iter = [];
xbase = x0;
fbase = f0;
xopt = x0;
fopt = f0;
exitflag = 0;
terminate = false;
target_reached = false;

if f0_real <= ftarget
    target_reached = true;
    terminate = true;
    maxit = 0;
    exitflag = get_exitflag("FTARGET_REACHED");
elseif nf >= MaxFunctionEvaluations
    terminate = true;
    maxit = 0;
    exitflag = get_exitflag("MAXFUN_REACHED");
end

for iter = 1:maxit
    xbase_iter_start = xbase;
    fbase_iter_start = fbase;
    iter_improved = false;

    % Search step before the regular polling loop.
    %
    % The memory list contains only directions generated by accepted polling
    % updates; it does not store directions generated by the pattern or momentum
    % steps. For each accepted polling update in block i, let block_step be the
    % accepted update step vector. If norm(block_step) > StepTolerance(i), we
    % store d = block_step / norm(block_step) together with stored_step =
    % norm(block_step).
    %
    % The list is bounded by productive_direction_memory_size. A new direction is
    % inserted at the front. If the list is full, the oldest stored direction is
    % dropped. A candidate direction is not stored when
    %     abs(d_old' * d_new) > 0.95
    % for an existing stored direction, so almost parallel or antiparallel
    % directions are treated as already represented.
    %
    % For each stored direction d, set
    %     step = max(mean(alpha_all), stored_step),
    % where stored_step is the accepted polling step length saved when d was
    % inserted into the memory list. It is not the latest block step size and is
    % not updated by later polling steps. If xbase + step * d improves the
    % objective, accept it and test at most two farther points along the same
    % direction. This is finite probing, not a line search.
    if options.use_productive_direction_memory && ~isempty(prod_memory) && nf < MaxFunctionEvaluations
        avg_alpha = mean(alpha_all);
        for m_idx = 1:numel(prod_memory)
            if nf >= MaxFunctionEvaluations
                break;
            end
            dir_vec = prod_memory(m_idx).direction;
            stored_step = prod_memory(m_idx).step;
            step = max(avg_alpha, stored_step);
            x_cand = xbase + step * dir_vec;
            [f_cand, f_cand_real, is_valid] = eval_fun(fun, x_cand);
            nf = nf + 1;
            fhist(nf) = f_cand_real;
            if output_xhist
                xhist(:, nf) = x_cand;
                if ~is_valid
                    invalid_points = [invalid_points, x_cand];
                end
            end
            if f_cand <= ftarget
                target_reached = true;
                terminate = true;
                exitflag = get_exitflag("FTARGET_REACHED");
            end
            if f_cand < fbase
                xbase = x_cand;
                fbase = f_cand;
                iter_improved = true;
                if target_reached
                    break;
                end
                [xbase, fbase, nf, fhist, xhist, invalid_points] = try_extrapolation( ...
                    fun, xbase, fbase, dir_vec, step * 2.0, nf, ...
                    MaxFunctionEvaluations, ftarget, fhist, xhist, ...
                    invalid_points, output_xhist);
                prod_memory(m_idx) = [];
                prod_memory = insert_memory_front(prod_memory, dir_vec, step);
                if fbase <= ftarget
                    target_reached = true;
                    terminate = true;
                    exitflag = get_exitflag("FTARGET_REACHED");
                end
                break;
            end
            if target_reached
                break;
            end
        end
    end

    % Baseline sorted block order. Ordinary direction cycling is retained in
    % grouped_direction_indices, with the block partition supplied by
    % divide_direction_set.m.
    for i = 1:num_blocks
        if terminate || nf >= MaxFunctionEvaluations
            break;
        end
        direction_indices = grouped_direction_indices{i};
        suboptions.MaxFunctionEvaluations = max(0, MaxFunctionEvaluations - nf);
        suboptions.ftarget = ftarget;
        suboptions.forcing_function = forcing_function;
        suboptions.reduction_factor = reduction_factor;
        suboptions.polling_inner = "opportunistic";
        suboptions.cycling_inner = 1;
        suboptions.iprint = 0;
        suboptions.FunctionEvaluations_exhausted = nf;
        suboptions.i_real = i;

        [sub_xopt, sub_fopt, sub_exitflag, sub_output] = inner_direct_search( ...
            fun, xbase, fbase, D(:, direction_indices), direction_indices, ...
            alpha_all(i), suboptions);
        num_visited_blocks = num_visited_blocks + 1;
        block_hist(num_visited_blocks) = i;
        if output_xhist
            xhist(:, (nf + 1):(nf + sub_output.nf)) = sub_output.xhist;
            invalid_points = [invalid_points, sub_output.invalid_points];
        end
        fhist((nf + 1):(nf + sub_output.nf)) = sub_output.fhist;
        nf = nf + sub_output.nf;
        fopt_all(i) = sub_fopt;
        xopt_all(:, i) = sub_xopt;
        grouped_direction_indices{i} = sub_output.direction_indices;

        xbase_before_block = xbase;
        update_base = (sub_fopt + reduction_factor(1) * forcing_function(alpha_all(i)) < fbase) ...
            || (isnan(fbase) && ~isnan(sub_fopt));
        if (sub_fopt + reduction_factor(3) * forcing_function(alpha_all(i)) < fbase) ...
                || (isnan(fbase) && ~isnan(sub_fopt))
            alpha_all(i) = alpha_all(i) * expand;
        elseif (sub_fopt + reduction_factor(2) * forcing_function(alpha_all(i)) >= fbase) ...
                || (isnan(sub_fopt) && ~isnan(fbase))
            alpha_all(i) = alpha_all(i) * shrink;
        end

        if sub_output.terminate
            terminate = true;
            exitflag = sub_exitflag;
            if sub_exitflag == get_exitflag("FTARGET_REACHED")
                target_reached = true;
                if update_base
                    xbase = sub_xopt;
                    fbase = sub_fopt;
                end
            end
            break;
        end
        if update_base
            xbase = sub_xopt;
            fbase = sub_fopt;
            block_step = sub_xopt - xbase_before_block;
            block_step_norm = norm(block_step);
            if options.use_productive_direction_memory && block_step_norm > StepTolerance(i)
                prod_memory = remember_direction( ...
                    prod_memory, block_step, block_step_norm, productive_direction_memory_size);
            end
        end
        if all(alpha_all < StepTolerance) || nf >= MaxFunctionEvaluations
            terminate = true;
            break;
        end
    end

    iter_step = xbase - xbase_iter_start;
    iter_step_norm = norm(iter_step);
    if fbase < fbase_iter_start
        iter_improved = true;
    end

    % Hooke-Jeeves-style pattern step after regular polling.
    % The original pattern-search idea was introduced by Hooke and Jeeves in
    % "Direct Search" Solution of Numerical and Statistical Problems (JACM,
    % 1961).
    %
    % If the polling step improves the base point, use the total accepted step in
    % this iteration to define
    %     iter_step   = xbase - xbase_iter_start,
    %     pattern_dir = iter_step / norm(iter_step),
    %     alpha_pat   = max(norm(iter_step), max(StepTolerance)).
    % First probe along pattern_dir with factors in [1, 2, 4]. If one of these
    % trial points improves the objective, keep it and stop here.
    %
    % If the pattern step is disabled or does not improve the objective, then
    % probe along momentum_dir with the same finite factors. The momentum
    % vector is an exponential moving average of pattern directions across
    % iterations:
    %     momentum = momentum_decay * momentum + (1 - momentum_decay) * pattern_dir.
    % The initial momentum vector is zero, so the first update gives
    %     momentum = (1 - momentum_decay) * pattern_dir.
    % Normalize it to get momentum_dir. Momentum is a fallback search step,
    % not a step that always follows pattern.
    if ~terminate && iter_improved && iter_step_norm > max(StepTolerance) && nf < MaxFunctionEvaluations ...
            && (options.use_sweep_pattern_direction || options.use_momentum_extrapolation)
        pattern_dir = iter_step / iter_step_norm;
        alpha_pat = max(iter_step_norm, max(StepTolerance));

        if options.use_momentum_extrapolation
            momentum = momentum_decay * momentum + (1.0 - momentum_decay) * pattern_dir;
            momentum_norm = norm(momentum);
            if momentum_norm > max(StepTolerance)
                momentum_dir = momentum / momentum_norm;
            else
                momentum_dir = [];
            end
        else
            momentum_dir = [];
        end

        factors = [1.0, 2.0, 4.0];
        x_pat = xbase;
        f_pat = fbase;
        best_dir = [];
        pat_improved = false;

        if options.use_sweep_pattern_direction
            for idx = 1:numel(factors)
                if nf >= MaxFunctionEvaluations
                    break;
                end
                factor = factors(idx);
                x_candidate = xbase + factor * alpha_pat * pattern_dir;
                [f_candidate, f_candidate_real, is_valid] = eval_fun(fun, x_candidate);
                nf = nf + 1;
                fhist(nf) = f_candidate_real;
                if output_xhist
                    xhist(:, nf) = x_candidate;
                    if ~is_valid
                        invalid_points = [invalid_points, x_candidate];
                    end
                end
                if f_candidate < f_pat
                    x_pat = x_candidate;
                    f_pat = f_candidate;
                    best_dir = pattern_dir;
                    pat_improved = true;
                else
                    break;
                end
                if f_candidate <= ftarget
                    target_reached = true;
                    break;
                end
            end
        end

        if ~target_reached && options.use_momentum_extrapolation && ~pat_improved && ~isempty(momentum_dir) ...
                && nf < MaxFunctionEvaluations
            for idx = 1:numel(factors)
                if nf >= MaxFunctionEvaluations
                    break;
                end
                factor = factors(idx);
                x_candidate = xbase + factor * alpha_pat * momentum_dir;
                [f_candidate, f_candidate_real, is_valid] = eval_fun(fun, x_candidate);
                nf = nf + 1;
                fhist(nf) = f_candidate_real;
                if output_xhist
                    xhist(:, nf) = x_candidate;
                    if ~is_valid
                        invalid_points = [invalid_points, x_candidate];
                    end
                end
                if f_candidate < f_pat
                    x_pat = x_candidate;
                    f_pat = f_candidate;
                    best_dir = momentum_dir;
                else
                    break;
                end
                if f_candidate <= ftarget
                    target_reached = true;
                    break;
                end
            end
        end

        if f_pat < fbase
            xbase = x_pat;
            fbase = f_pat;
            if options.use_productive_direction_memory && ~isempty(best_dir)
                prod_memory = remember_direction( ...
                    prod_memory, best_dir, alpha_pat, productive_direction_memory_size);
            end
        end
        if target_reached
            terminate = true;
            exitflag = get_exitflag("FTARGET_REACHED");
        end
    end

    [~, index] = min(fopt_all, [], "omitnan");
    if ~isempty(index) && fopt_all(index) < fopt
        fopt = fopt_all(index);
        xopt = xopt_all(:, index);
    end
    if fbase < fopt
        fopt = fbase;
        xopt = xbase;
    end

    if nf >= MaxFunctionEvaluations || all(alpha_all < StepTolerance)
        terminate = true;
    end
    if output_alpha_hist
        alpha_hist = [alpha_hist, alpha_all(:)];
    end
    if terminate
        break;
    end
end

if target_reached
    exitflag = get_exitflag("FTARGET_REACHED");
elseif nf >= MaxFunctionEvaluations
    exitflag = get_exitflag("MAXFUN_REACHED");
elseif all(alpha_all < StepTolerance)
    exitflag = get_exitflag("SMALL_ALPHA");
end

output.funcCount = nf;
if output_block_hist
    output.blocks_hist = block_hist(1:num_visited_blocks);
end
if output_alpha_hist
    output.alpha_hist = alpha_hist;
end
if output_xhist
    output.xhist = xhist(:, 1:nf);
    output.invalid_points = invalid_points;
end
if output_grad_hist
    output.grad_hist = grad_hist;
    output.grad_xhist = grad_xhist;
    output.grad_iter = grad_iter;
end
output.fhist = fhist(1:nf);
output.message = get_bds_exit_message(exitflag);

end

function [xbest, fbest, nf, fhist, xhist, invalid_points] = try_extrapolation( ...
    fun, xbase, fbase, direction, step, nf, MaxFunctionEvaluations, ...
    ftarget, fhist, xhist, invalid_points, output_xhist)
xbest = xbase;
fbest = fbase;
for k = 1:2
    if nf >= MaxFunctionEvaluations
        break;
    end
    xcand = xbest + step * direction;
    [fcand, fcand_real, is_valid] = eval_fun(fun, xcand);
    nf = nf + 1;
    fhist(nf) = fcand_real;
    if output_xhist
        xhist(:, nf) = xcand;
        if ~is_valid
            invalid_points = [invalid_points, xcand];
        end
    end
    if fcand < fbest
        xbest = xcand;
        fbest = fcand;
        if fcand <= ftarget
            break;
        end
        step = step * 2.0;
    else
        break;
    end
end
end

function prod_memory = remember_direction(prod_memory, direction, step, mem_size)
direction = direction(:);
norm_direction = norm(direction);
if norm_direction == 0
    return;
end
direction = direction / norm_direction;

is_dup = false;
for k = 1:numel(prod_memory)
    if abs(prod_memory(k).direction' * direction) > 0.95
        is_dup = true;
        break;
    end
end
if is_dup
    return;
end

if numel(prod_memory) >= mem_size
    prod_memory(end) = [];
end
prod_memory = insert_memory_front(prod_memory, direction, step);
end

function prod_memory = insert_memory_front(prod_memory, direction, step)
entry.direction = direction(:);
entry.step = double(step);
if isempty(prod_memory)
    prod_memory = entry;
else
    prod_memory = [entry, prod_memory];
end
end

function message = get_bds_exit_message(exitflag)
switch exitflag
    case get_exitflag("FTARGET_REACHED")
        message = "The target of the objective function is reached.";
    case get_exitflag("MAXFUN_REACHED")
        message = "The maximum number of function evaluations is reached.";
    case get_exitflag("MAXIT_REACHED")
        message = "The maximum number of iterations is reached.";
    case get_exitflag("SMALL_ALPHA")
        message = "The StepTolerance of the step size is reached.";
    case get_exitflag("SMALL_OBJECTIVE_CHANGE")
        message = "The change of the function value is small.";
    case get_exitflag("SMALL_ESTIMATE_GRADIENT")
        message = "The estimated gradient is small.";
    otherwise
        message = "Unknown exitflag";
end
end
