name: Use MatCUTEst in GitHub Actions

on:
  # Trigger the workflow on push or pull request
  push:
  #pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 18 * * *'
  # Trigger the workflow manually
  workflow_dispatch:

jobs:

  test:

    name: Demo

    runs-on: ubuntu-latest

    steps:
      - name: Clone MatCUTEst
        uses: actions/checkout@v3.5.2
        with:
          repository: equipez/matcutest_compiled
          path: matcutest

      - name: Clone bds_new_framework
        uses: actions/checkout@v3.5.2
        with:
          repository: Lht97/bds_new_framework
          path: bds_new_framework


      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2-beta

      - name: Run tests
        uses: matlab-actions/run-command@v1.2.0
        with:
          command: |
            root_dir = pwd()

            % Install MatCUTEst
            cd(fullfile(root_dir, 'matcutest'));
            install(); cd(root_dir);

            % Check the installation
            help matcutest, which('macup'), which('decup'), which('secup')
            macup('akiva')

            % Conduct your tests
            cd(fullfile(root_dir, 'bds_new_framework'))
            path = pwd;
            path_tests = fullfile(path, 'tests');
            cd(path_tests)
            parameters.matcutest_github_actions = '/home/runner/.local/matcutest/mtools/src';
            parameters.solvers_invoke = ["blockwise_direct_search", "newuoa"];
            parameters.solvers_label = ["GS", "newuoa"];
            parameters.solver_tag = ["GS", "newuoa"];
            testbds_input(parameters)
