name: Profile cbds with different tuning window sizes and function tolerances, small

on:
  # Trigger the workflow on # push or pull request
  # push:
  # Trigger the workflow manually
  schedule:
  - cron: '0 0 */2 * *'
  workflow_dispatch:

jobs:
  test:
    name: Profile cbds with different tuning window sizes and function tolerances, small
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        matlab: [latest]
        dim: [small]
        with_optim_toolbox: [yes]
        summarize_log_ratio_profiles: [false]
        feature: [plain, noisy_1e-3, linearly_transformed, random_nrotation_noisy_1e-3]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: development

      - name: Checkout OptiProfiler
        uses: actions/checkout@v4
        with:
          repository: optiprofiler/optiprofiler
          path: optiprofiler
          submodules: recursive
          ref: c71d78a4dd0838fb1925e3c97885aded39fffe38

      - name: Install Texlive
        run: sudo apt-get update && sudo apt-get install texlive

      - name: Check whether LaTeX is installed
        run: pdflatex --version

      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.os }}-${{ matrix.matlab }}-${{ matrix.with_optim_toolbox }}

      - name: Set up MATLAB with optimization toolbox
        if: ${{ matrix.with_optim_toolbox == 'yes' }}
        uses: matlab-actions/setup-matlab@v2.1.2
        with:
          release: ${{ matrix.matlab }}
          products: Optimization_Toolbox

      - name: Run test
        uses: matlab-actions/run-command@v2.1.1
        with:
            command: |
              root_dir = pwd()
              ls
  
              % Setup optiprofiler
              cd(fullfile(root_dir, 'optiprofiler'));
              setup
              cd(root_dir);
  
              % Setup bds
              setup
              cd(fullfile(root_dir, 'tests'));
              addpath(pwd);
  
              % profile
              cd(fullfile(root_dir, 'tests', 'tuning'));
              parameters.window_size = 10:5:20;
              parameters.func_tol =10.^(-6:-2:-12);
              options.feature_name = '${{ matrix.feature }}';
              options.dim = '${{ matrix.dim }}';
              options.summarize_log_ratio_profiles = ${{ matrix.summarize_log_ratio_profiles }};
              tuning_script_optiprofiler(parameters, options);

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tuning_window_size_func_tol_small
          path: ./tests/tuning/tuning_data/**

 