name: Performance profile of blockwise_direct_search

on:
  # Trigger the workflow on push or pull request
  push:
  # Trigger the workflow manually
  workflow_dispatch:

env:
    GFORTRAN_VERSION: 12

jobs:

  test:

    name: Profile blockwise direct search.
    runs-on: ${{matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        matlab: [latest]
        dim: [small, big]
        with_optim_toolbox: [yes]
        solver: [blockwise_direct_search]
        solver_blocks_strategy: [Gauss-Seidel]
        competitor: [blockwise_direct_search, matlab_fminunc, matlab_fminsearch]
        competitor_type: [none, bfgs, lbfgs, dfp, steepdesc]
        competitor_blocks_strategy: [none, Randomized_array]
        exclude:
          - competitor: blockwise_direct_search
            competitor_type: bfgs
            competitor_blocks_strategy: none
          - competitor: blockwise_direct_search
            competitor_type: bfgs
            competitor_blocks_strategy: Randomized_array
          - competitor: blockwise_direct_search
            competitor_type: lbfgs
            competitor_blocks_strategy: none
          - competitor: blockwise_direct_search
            competitor_type: lbfgs
            competitor_blocks_strategy: Randomized_array
          - competitor: blockwise_direct_search
            competitor_type: dfp
            competitor_blocks_strategy: none
          - competitor: blockwise_direct_search
            competitor_type: dfp
            competitor_blocks_strategy: Randomized_array
          - competitor: blockwise_direct_search
            competitor_type: steepdesc
            competitor_blocks_strategy: none
          - competitor: blockwise_direct_search
            competitor_type: steepdesc
            competitor_blocks_strategy: Randomized_array
          - competitor: blockwise_direct_search
            competitor_type: none
            competitor_blocks_strategy: none

          - competitor: matlab_fminunc
            competitor_type: none
            competitor_blocks_strategy: none
          - competitor: matlab_fminunc
            competitor_type: none
            competitor_blocks_strategy: Randomized_array
          - competitor: matlab_fminunc
            competitor_type: bfgs
            competitor_blocks_strategy: Randomized_array
          - competitor: matlab_fminunc
            competitor_type: lbfgs
            competitor_blocks_strategy: Randomized_array
          - competitor: matlab_fminunc
            competitor_type: dfp
            competitor_blocks_strategy: Randomized_array
          - competitor: matlab_fminunc
            competitor_type: steepdesc
            competitor_blocks_strategy: Randomized_array

          - competitor: matlab_fminsearch
            competitor_type: bfgs
            competitor_blocks_strategy: none
          - competitor: matlab_fminsearch
            competitor_type: bfgs
            competitor_blocks_strategy: Randomized_array
          - competitor: matlab_fminsearch
            competitor_type: lbfgs
            competitor_blocks_strategy: none
          - competitor: matlab_fminsearch
            competitor_type: lbfgs
            competitor_blocks_strategy: Randomized_array
          - competitor: matlab_fminsearch
            competitor_type: dfp
            competitor_blocks_strategy: none
          - competitor: matlab_fminsearch
            competitor_type: dfp
            competitor_blocks_strategy: Randomized_array
          - competitor: matlab_fminsearch
            competitor_type: steepdesc
            competitor_blocks_strategy: none
          - competitor: matlab_fminsearch
            competitor_type: steepdesc
            competitor_blocks_strategy: Randomized_array
          - competitor: matlab_fminsearch
            competitor_type: none
            competitor_blocks_strategy: Randomized_array

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Clone PRIMA
        uses: actions/checkout@v3
        with:
          repository: libprima/prima
          path: prima

      - name: Clone MatCUTEst
        uses: actions/checkout@v3
        with:
          repository: equipez/matcutest_compiled
          path: matcutest

      - name: Link gfortran for MATLAB on Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: bash .github/scripts/link_gfortran ${{ env.GFORTRAN_VERSION }}

      - name: Install epstopdf and ghostscript
        if: startsWith(matrix.os, 'ubuntu')
        run: bash .github/scripts/install_epstopdf && bash .github/scripts/install_ghostscript

      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v3.3.1
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.os }}-${{ matrix.matlab }}-${{ matrix.with_optim_toolbox }}

      - name: Set up MATLAB with optimization toolbox
        if: ${{ matrix.with_optim_toolbox == 'yes' }}
        uses: matlab-actions/setup-matlab@v2-beta
        with:
          release: ${{ matrix.matlab }}
          products: Optimization_Toolbox

      - name: Run tests
        uses: matlab-actions/run-command@v1.2.0
        with:
          command: |
            root_dir = pwd()

            % Install MatCUTEst
            cd(fullfile(root_dir, 'matcutest'));
            install(); cd(root_dir);

            % Compile prima
            path_prima = fullfile(root_dir, 'prima');
            cd(path_prima);
            setup

            % Conduct your tests
            path_tests = fullfile(root_dir, 'tests');
            cd(path_tests)
            if "${{ matrix.dim }}" == "small"
                parameters.problems_mindim = 1;
                parameters.problems_maxdim = 5;
            elseif "${{ matrix.dim }}" == "big"
                parameters.problems_mindim = 6;
                parameters.problems_maxdim = 100;
            end
            parameters.blocks_strategy = ["Gauss-Seidel", "Randomized_array"];
            parameters.parallel = true;
            parameters.fminunc_type = "${{ matrix.competitor_type }}";
            parameters.solvers_invoke = ["${{ matrix.solver }}", "${{ matrix.competitor }}"];
            parameters.blocks_strategy = ["${{ matrix.solver_blocks_strategy }}", "${{ matrix.competitor_blocks_strategy }}"];
            testbds_input(parameters);

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: my-artifacts
          path: ./tests/testdata
